const app = document.querySelector('#app');
const users = [
  { email: 'proyectos@fullcheck.cl', password: '@Fam7728k', role: 'admin', clientId: null },
  { email: 'cliente@fullcheck.cl', password: '@Cliente123', role: 'client', clientId: 1 },
];
const state = {
  user: null,
  view: 'dashboard',
  selectedClientId: 1,
  theme: 'light',
  nextTicket: 2,
  settings: { days: 'Lunes a viernes', open: '09:00', close: '18:00', message: 'Solicitudes ingresadas fuera de horario serán respondidas el día hábil siguiente.' },
  terms: 'El trabajo valorizado inicia una vez aprobado por el cliente y validado el pago por FullCheck. Los plazos se cuentan en días hábiles de lunes a viernes. Cambios fuera del alcance aprobado podrán generar una nueva valorización.',
  notifications: [
    { id: 1, text: 'Nuevo mensaje de FullCheck', time: 'Hoy 10:20', view: 'messages' },
    { id: 2, text: 'Reunión confirmada para el 15 mayo', time: 'Hoy 09:30', view: 'meetings' },
    { id: 3, text: 'Reporte de avance publicado', time: 'Ayer', view: 'deliverables' },
  ],
  clients: [
    { id: 1, name: 'Constructora Andina SpA', contact: 'María González', email: 'cliente@fullcheck.cl', password: '@Cliente123', plan: 'Mantención Web', initials: 'CA' },
    { id: 2, name: 'Clínica Dental Sonríe', contact: 'Felipe Rojas', email: 'felipe@sonrie.cl', password: '@Cliente123', plan: 'Web + Soporte', initials: 'CS' },
  ],
  projects: [
    { id: 1, clientId: 1, name: 'Sitio web corporativo', phase: 'Desarrollo', status: 'En progreso', progress: 68, due: '28 mayo', next: 'Validar textos de servicios', visible: true },
    { id: 2, clientId: 1, name: 'Optimización SEO', phase: 'Revisión', status: 'En revisión', progress: 82, due: '10 junio', next: 'Aprobar palabras clave', visible: true },
    { id: 3, clientId: 2, name: 'Portal de reservas', phase: 'Levantamiento', status: 'Planificación', progress: 35, due: '18 junio', next: 'Confirmar horarios', visible: true },
  ],
  milestones: [
    { id: 1, clientId: 1, projectId: 1, title: 'Subida de imágenes', date: '05/05/2026', assignedTo: 'FullCheck', status: 'Completado', visible: true },
    { id: 2, clientId: 1, projectId: 1, title: 'Validación de textos', date: '09/05/2026', assignedTo: 'Cliente', status: 'Pendiente', visible: true },
    { id: 3, clientId: 1, projectId: 2, title: 'Auditoría inicial SEO', date: '10/05/2026', assignedTo: 'FullCheck', status: 'Completado', visible: true },
  ],
  updates: [{ id: 1, clientId: 1, projectId: 1, title: 'Avance diseño home', text: 'Se completó estructura principal y se trabaja en secciones internas.', date: '11 mayo', visible: true }],
  requests: [{ id: 1, clientId: 1, projectId: 1, title: 'Cambiar texto principal', detail: 'Actualizar bajada principal.', status: 'Nueva', progress: 10, complexity: 'Media', businessDays: 3, dueDate: 'Día hábil 3', response: '', date: 'Hoy 09:40', visible: true }],
  tickets: [{ id: 1, number: 'FC-TK-0001', clientId: 1, projectId: 1, title: 'Formulario no llega al correo', priority: 'Alta', status: 'En revisión', response: 'Estamos revisando SMTP.', date: '10 mayo', visible: true }],
  meetings: [{ id: 1, clientId: 1, projectId: 1, title: 'Revisión avance sitio web', date: '15 mayo', time: '10:30', status: 'Confirmada', link: 'https://meet.google.com/demo', notes: 'Revisar home y servicios.', visible: true }],
  deliverables: [{ id: 1, clientId: 1, projectId: 1, title: 'Reporte avance diseño home', type: 'PDF', url: 'https://example.com/reporte-avance.pdf', status: 'Publicado', date: '11 mayo', visible: true }],
  valuations: [{ id: 1, clientId: 1, projectId: 1, title: 'Sección adicional de testimonios', detail: 'Diseño y desarrollo de nueva sección.', price: 85000, complexity: 'Media', businessDays: 3, dueDate: 'Día hábil 3', status: 'Pendiente aprobación', paymentProof: '', acceptedTerms: false, visible: true }],
  catalog: [
    { id: 1, title: 'Sección adicional web', category: 'Desarrollo', description: 'Diseño y desarrollo de una sección adicional administrable o informativa.', price: 85000, complexity: 'Media', businessDays: 3, image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80', visible: true },
    { id: 2, title: 'Reporte gráfico ejecutivo', category: 'Reportes', description: 'Preparación de reporte visual con gráficos, indicadores y resumen ejecutivo.', price: 65000, complexity: 'Baja', businessDays: 2, image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80', visible: true },
    { id: 3, title: 'Optimización SEO base', category: 'Marketing', description: 'Ajustes técnicos iniciales, metadatos, estructura y recomendaciones SEO.', price: 120000, complexity: 'Alta', businessDays: 5, image: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?auto=format&fit=crop&w=900&q=80', visible: true },
  ],
  contracts: [],
  files: [{ id: 1, clientId: 1, projectId: 1, title: 'Logo Constructora PNG', type: 'Logo', status: 'Revisado', date: '09 mayo', visible: true }],
  messages: [{ id: 1, clientId: 1, from: 'FullCheck', text: 'Estamos revisando tus solicitudes.', time: 'Hoy 10:20', visible: true }],
};
const icons = { dashboard:'⌂', clients:'♙', projects:'⌗', requests:'▢', tickets:'◌', meetings:'▱', deliverables:'▤', valuations:'$', contracts:'◇', messages:'▭', terms:'☰', settings:'⚙', logout:'↪', bell:'◍', add:'+' };
const icon = key => `<span class="line-icon">${icons[key] || '•'}</span>`;
const isAdmin = () => state.user?.role === 'admin';
const clientId = () => isAdmin() ? state.selectedClientId : state.user.clientId;
const client = () => state.clients.find(c => c.id === clientId()) || state.clients[0];
const scoped = arr => arr.filter(x => x.clientId === clientId()).filter(x => isAdmin() || x.visible !== false);
const projectName = id => state.projects.find(p => p.id === id)?.name || 'Proyecto general';
const money = n => `$${Number(n || 0).toLocaleString('es-CL')}`;
function businessDaysByComplexity(complexity){ return { Baja: 1, Media: 3, Alta: 5, Avanzada: 10 }[complexity] || 3; }
function addBusinessDays(days){ let date = new Date(); let added = 0; while (added < days) { date.setDate(date.getDate() + 1); const day = date.getDay(); if (day !== 0 && day !== 6) added += 1; } return date.toLocaleDateString('es-CL', { weekday: 'short', day: '2-digit', month: 'short' }); }
function progressByStatus(status){ return { Nueva: 10, 'En revisión': 25, 'En ejecución': 60, Completada: 100, Cerrada: 100, Rechazada: 100 }[status] || 10; }
function notify(text, view = state.view){ state.notifications.unshift({ id: Date.now(), text, time: 'Ahora', view }); }
function setView(view){ state.view = view; render(); }
function toggleTheme(){ state.theme = state.theme === 'dark' ? 'light' : 'dark'; render(); }
function login(e){ e.preventDefault(); const email = val('email').toLowerCase(); const password = val('password'); const u = users.find(x => x.email === email && x.password === password); if(!u) return loginView('Credenciales incorrectas.'); state.user = u; state.view = 'dashboard'; if(u.clientId) state.selectedClientId = u.clientId; notify('Sesión iniciada correctamente.'); render(); }
function logout(){ state.user = null; loginView(); }
function val(id){ return document.getElementById(id)?.value.trim() || ''; }
function loginView(error=''){ app.innerHTML = `<main class="login-page"><section class="login-card"><div class="brand"><strong>full<span>checkPro</span></strong><em>Portal clientes</em></div><h1>Acceso al portal</h1><p>Ingresa con tus credenciales asignadas por FullCheck.</p>${error ? `<div class="login-error">${error}</div>` : ''}<form onsubmit="login(event)"><label>Email<input id="email" type="email" required placeholder="correo@empresa.cl"></label><label>Clave<input id="password" type="password" required placeholder="Clave"></label><button class="primary-button">Entrar</button></form></section></main>`; }
function nav(){ const adminItems = [['dashboard','Panel'],['clients','Clientes'],['projects','Proyectos'],['requests','Solicitudes'],['tickets','Tickets'],['meetings','Reuniones'],['deliverables','Entregables'],['valuations','Valorizaciones'],['contracts','Contratos'],['messages','Mensajería'],['terms','Condiciones'],['settings','Configuración']]; const clientItems = [['dashboard','Inicio'],['projects','Avances'],['requests','Solicitudes'],['tickets','Tickets'],['meetings','Reuniones'],['deliverables','Entregables'],['valuations','Servicios'],['contracts','Contratos'],['messages','Mensajería'],['terms','Condiciones']]; return (isAdmin()?adminItems:clientItems).map(([v,t])=>`<button class="${state.view===v?'active':''}" onclick="setView('${v}')">${icon(v)} ${t}</button>`).join(''); }
function shell(content){ document.body.dataset.theme = state.theme; app.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="brand"><strong>full<span>checkPro</span></strong><em>${isAdmin()?'Panel admin':'Portal cliente'}</em></div><div class="local-badge">● clientes.fullcheck.cl</div><nav><small>MENÚ</small>${nav()}</nav><button class="sidebar-footer" onclick="logout()">${icon('logout')} Cerrar sesión</button></aside><div class="main-area"><header class="topbar"><input class="search-input" placeholder="Buscar..."><div class="topbar-actions"><button class="ghost-button" onclick="toggleTheme()">${state.theme === 'dark' ? 'Modo claro' : 'Modo oscuro'}</button><button class="alert-button" onclick="openNotifications()">${icon('bell')} ${state.notifications.length}</button>${!isAdmin()?`<button class="primary-button" onclick="openRequest('Solicitud')">${icon('add')} Nueva solicitud</button>`:''}</div></header>${content}</div></div>`; }
function stat(label,value,kind='blue'){ return `<article class="stat-card ${kind}"><div><p>${label}</p><strong>${value}</strong></div></article>`; }
function page(title, subtitle, body, action=''){ return `<main class="content-grid"><section class="hero-card"><div><span class="eyebrow">${subtitle}</span><h1>${title}</h1></div>${action}</section>${body}</main>`; }
function adminSelector(){ return `<label class="client-selector">Cliente<select onchange="state.selectedClientId=Number(this.value);render()">${state.clients.map(c=>`<option value="${c.id}" ${c.id===state.selectedClientId?'selected':''}>${c.name}</option>`).join('')}</select></label>`; }
function dashboard(){ const projects=scoped(state.projects); const c=client(); const body = `<section class="stats-grid">${stat('Proyectos',projects.length)}${stat('Solicitudes',scoped(state.requests).length,'purple')}${stat('Tickets abiertos',scoped(state.tickets).filter(t=>!['Resuelto','Cerrado'].includes(t.status)).length,'orange')}${stat('Valorizaciones',scoped(state.valuations).length,'green')}</section><section class="panel wide">${operationalSummary()}</section><section class="panel wide"><div class="section-title"><div><span class="eyebrow">Pipeline</span><h2>Estado general</h2></div></div>${pipeline()}</section><section class="panel"><div class="section-title"><div><span class="eyebrow">Mensajería</span><h2>Últimos mensajes</h2></div><button class="ghost-button" onclick="setView('messages')">Ver todo</button></div>${dashboardMessages()}</section><section class="panel"><div class="section-title"><div><span class="eyebrow">Calendario</span><h2>Agenda visual</h2></div><button class="ghost-button" onclick="setView('meetings')">Abrir</button></div>${calendarPreview()}</section><section class="panel"><div class="section-title"><div><span class="eyebrow">Últimos avances</span><h2>Bitácora</h2></div></div>${updates()}</section><section class="panel"><div class="section-title"><div><span class="eyebrow">Actividad</span><h2>Movimiento reciente</h2></div></div>${activityFeed()}</section>`; shell(page(isAdmin()?'Gestión FullCheck':c.name,isAdmin()?'Panel operativo sincronizado':'Portal cliente',body,isAdmin()?adminSelector():'')); }
function pipeline(){ const stages=['Planificación','Levantamiento','Diseño','Desarrollo','Revisión','Entrega']; const projects=scoped(state.projects); return `<div class="pipeline-board">${stages.map(s=>`<div class="pipeline-column"><strong>${s}</strong>${projects.filter(p=>p.phase===s||p.status.includes(s)).map(p=>`<article class="pipeline-card"><span>${p.name}</span><small>${p.progress}% · ${p.status}</small>${isAdmin()?`<button class="ghost-button" onclick="setPhase(${p.id},'${s}')">Mover aquí</button>`:''}</article>`).join('')||'<small>Sin proyectos</small>'}</div>`).join('')}</div>`; }
function operationalSummary(){ const requests=scoped(state.requests).filter(x=>['Nueva','En revisión'].includes(x.status)); const tickets=scoped(state.tickets).filter(x=>!['Resuelto','Cerrado'].includes(x.status)); const meetings=scoped(state.meetings).filter(x=>['Solicitada','Confirmada'].includes(x.status)); const approvals=scoped(state.valuations).filter(x=>x.status==='Pendiente aprobación'); const cards=[['Solicitudes por revisar',requests.length,'requests'],['Tickets activos',tickets.length,'tickets'],['Reuniones próximas',meetings.length,'meetings'],['Extras por aprobar',approvals.length,'valuations']]; return `<div class="ops-board">${cards.map(([title,total,view])=>`<button onclick="setView('${view}')"><strong>${total}</strong><span>${title}</span></button>`).join('')}</div>`; }
function projectsView(){ const body=`<section class="panel wide">${projectVisualSummary()}${scoped(state.projects).map(projectCard).join('')}</section>`; shell(page('Proyectos y avances','Línea de tiempo, hitos y seguimiento visual',body,isAdmin()?`${adminSelector()}<button class="primary-button" onclick="openMilestoneModal()">Agregar hito</button>`:`<button class="primary-button" onclick="openOnboarding()">Ver onboarding</button>`)); }
function projectVisualSummary(){ const projects=scoped(state.projects); const avg=Math.round(projects.reduce((a,p)=>a+p.progress,0)/(projects.length||1)); const pending=scoped(state.milestones).filter(m=>m.status!=='Completado').length; return `<div class="visual-summary"><div><span>Avance global</span><strong>${avg}%</strong></div><div><span>Proyectos activos</span><strong>${projects.length}</strong></div><div><span>Hitos pendientes</span><strong>${pending}</strong></div></div>`; }
function projectCard(p){ return `<article class="project-card project-card-visual"><div class="card-header"><div><span class="eyebrow">${p.phase}</span><h3>${p.name}</h3></div><span class="pill">${p.status}</span></div><div class="progress-wrap"><div class="progress-info"><span>Avance</span><strong>${p.progress}%</strong></div><div class="progress-bar"><span style="width:${p.progress}%"></span></div></div><div class="project-meta"><span>Entrega: ${p.due}</span><span>Próximo paso: ${p.next}</span></div>${projectTimeline(p.id)}${isAdmin()?`<div class="admin-project-actions"><input type="number" value="${p.progress}" onchange="setProgress(${p.id},this.value)"><input value="${p.phase}" onchange="setPhase(${p.id},this.value)"></div>${controls('projects',p.id)}`:''}</article>`; }
function projectTimeline(projectId){ const rows=scoped(state.milestones).filter(m=>m.projectId===projectId); return `<div class="project-timeline"><div class="timeline-title"><strong>Hitos del proyecto</strong>${isAdmin()?`<button class="ghost-button" onclick="openMilestoneModal(${projectId})">Asignar hito</button>`:''}</div>${rows.map(m=>`<div class="timeline-point ${m.status==='Completado'?'done':''}"><i></i><div><strong>${m.title}</strong><span>${m.date} · Asignado a ${m.assignedTo} · ${m.status}</span></div>${isAdmin()?`<button class="ghost-button" onclick="toggleMilestone(${m.id})">${m.status==='Completado'?'Reabrir':'Completar'}</button>`:''}</div>`).join('') || '<p class="empty-state">Sin hitos registrados.</p>'}</div>`; }
function moduleList(items,type){ return `<div class="item-list">${items.map(x=>`<div class="list-item"><div><strong>${x.number?x.number+' · ':''}${x.title}</strong><span>${x.projectId?projectName(x.projectId)+' · ':''}${x.date||''} ${x.detail||''}</span>${type==='requests'?requestSla(x):''}${type==='valuations'?valuationSummary(x):''}${x.response?`<p class="ticket-response">Respuesta: ${x.response}</p>`:''}${x.url?`<a class="report-link" href="${x.url}" target="_blank">Abrir ${x.type}</a>` : ''}</div><div class="item-actions"><span class="pill soft">${x.status||x.type}</span>${actions(type,x)}</div></div>`).join('')||'<p class="empty-state">Sin registros.</p>'}</div>`; }
function requestSla(x){ return `<div class="sla-box"><span>Complejidad: ${x.complexity || 'Media'}</span><span>Plazo: ${x.businessDays || 3} días hábiles</span><span>Entrega estimada: ${x.dueDate || 'Por confirmar'}</span><div class="mini-progress"><span style="width:${x.progress || progressByStatus(x.status)}%"></span></div><small>Avance requerimiento: ${x.progress || progressByStatus(x.status)}%</small></div>`; }
function valuationSummary(x){ return `<div class="sla-box"><span>Valor: ${money(x.price)}</span><span>Complejidad: ${x.complexity || 'Media'}</span><span>Plazo: ${x.businessDays || 3} días hábiles</span><span>Entrega estimada: ${x.dueDate || 'Por confirmar'}</span><span>Condiciones: ${x.acceptedTerms ? 'Aceptadas' : 'Pendientes'}</span><span>Comprobante: ${x.paymentProof || 'No adjuntado'}</span></div>`; }
function actions(type,x){ let a=''; if(!isAdmin() && type==='valuations' && x.status==='Pendiente aprobación') a+=`<button class="ghost-button" onclick="approveValuation(${x.id})">Aprobar y pagar</button><button class="danger-button" onclick="rejectValuation(${x.id})">Rechazar</button>`; if(!isAdmin()) return a; if(type==='requests') a+=`<button class="ghost-button" onclick="manageRequest(${x.id})">Gestionar</button>`; if(type==='tickets') a+=`<button class="ghost-button" onclick="answerTicket(${x.id})">Responder</button>`; if(type==='meetings') a+=`<button class="ghost-button" onclick="editMeeting(${x.id})">Gestionar</button>`; if(type==='valuations') a+=`<button class="ghost-button" onclick="manageValuation(${x.id})">Gestionar</button>`; return a+controls(type,x.id); }
function controls(col,id){ const it=state[col].find(x=>x.id===id); return `<div class="admin-controls"><button class="ghost-button" onclick="toggleVisible('${col}',${id})">${it.visible===false?'Publicar':'Ocultar'}</button><button class="danger-button" onclick="removeItem('${col}',${id})">Eliminar</button></div>`; }
function genericView(type,title,subtitle,button){ const data={requests:state.requests,tickets:state.tickets,meetings:state.meetings,deliverables:state.deliverables,valuations:state.valuations,files:state.files}[type]; shell(page(title,subtitle,`<section class="panel wide">${moduleList(scoped(data),type)}</section>`,button||'')); }
function valuationsView(){ const action=isAdmin()?`<button class="primary-button" onclick="openCatalogModal()">Nuevo servicio</button><button class="primary-button" onclick="openValuationModal()">Valorizar extra</button>`:''; shell(page('Valorizaciones','Catálogo, solicitudes extra y precios',`<section class="panel wide"><div class="section-title"><div><span class="eyebrow">Catálogo</span><h2>Servicios y productos definidos</h2></div></div>${catalogGrid()}<div class="section-title spaced"><div><span class="eyebrow">Historial</span><h2>Valorizaciones emitidas</h2></div></div>${moduleList(scoped(state.valuations),'valuations')}</section>`,action)); }
function catalogGrid(){ const items=state.catalog.filter(x=>isAdmin()||x.visible!==false); return `<div class="catalog-grid">${items.map(x=>`<article class="catalog-card"><img src="${x.image}" alt="${x.title}"><div><span class="eyebrow">${x.category}</span><h3>${x.title}</h3><p>${x.description}</p><div class="catalog-meta"><strong>${money(x.price)}</strong><span>${x.businessDays} días hábiles · ${x.complexity}</span></div>${isAdmin()?`<div class="admin-controls"><button class="ghost-button" onclick="createValuationFromCatalog(${x.id})">Valorizar</button><button class="ghost-button" onclick="toggleVisible('catalog',${x.id})">${x.visible===false?'Publicar':'Ocultar'}</button><button class="danger-button" onclick="removeItem('catalog',${x.id})">Eliminar</button></div>`:`<button class="primary-button" onclick="requestContract(${x.id})">Solicitar contratación</button>`}</div></article>`).join('') || '<p class="empty-state">Sin servicios definidos.</p>'}</div>`; }
function updates(){ return moduleList(scoped(state.updates),'updates'); }
function meetings(){ return moduleList(scoped(state.meetings),'meetings'); }
function dashboardMessages(){ const msgs=scoped(state.messages).slice(-3).reverse(); return `<div class="support-chat compact">${msgs.map(m=>`<div class="chat-message ${m.from==='Cliente'?'client':'support'}"><strong>${m.from}</strong><p>${m.text}</p><span>${m.time}</span></div>`).join('') || '<p class="empty-state">Sin mensajes recientes.</p>'}</div>`; }
function calendarPreview(){ const items=scoped(state.meetings).slice(0,4); return `<div class="calendar-strip">${items.map(m=>`<button onclick="setView('meetings')"><strong>${m.date}</strong><span>${m.time}</span><small>${m.title}</small></button>`).join('') || '<p class="empty-state">Sin reuniones próximas.</p>'}</div>`; }
function activityFeed(){ const rows=[...scoped(state.updates).map(x=>({t:x.title,d:x.date,v:'projects'})),...scoped(state.requests).map(x=>({t:x.title,d:x.date,v:'requests'})),...scoped(state.tickets).map(x=>({t:x.number+' · '+x.title,d:x.date,v:'tickets'})),...scoped(state.deliverables).map(x=>({t:x.title,d:x.date,v:'deliverables'}))].slice(0,6); return `<div class="item-list">${rows.map(r=>`<button class="activity-row" onclick="setView('${r.v}')"><strong>${r.t}</strong><span>${r.d}</span></button>`).join('') || '<p class="empty-state">Sin actividad reciente.</p>'}</div>`; }
function messagesView(){ shell(page('Mensajería','Comunicación con soporte',`<section class="panel wide"><div class="support-chat">${scoped(state.messages).map(m=>`<div class="chat-message ${m.from==='Cliente'?'client':'support'}"><strong>${m.from}</strong><p>${m.text}</p><span>${m.time}</span></div>`).join('')}<form class="chat-compose" onsubmit="sendMessage(event)"><input id="msg" placeholder="Escribe un mensaje..."><button class="primary-button">Enviar</button></form></div></section>`)); }
function clientsView(){ shell(page('Clientes','Accesos y datos relacionados',`<section class="panel wide"><div class="client-grid">${state.clients.map(c=>`<article class="client-summary"><div class="client-card"><div class="avatar">${c.initials}</div><div><h3>${c.name}</h3><p>${c.email} · ${c.plan}</p></div></div><div class="admin-controls"><button class="ghost-button" onclick="state.selectedClientId=${c.id};setView('dashboard')">Seleccionar</button><button class="danger-button" onclick="deleteClient(${c.id})">Eliminar cliente y datos</button></div></article>`).join('')}</div></section>`,`<button class="primary-button" onclick="openClientModal()">Crear cliente</button>`)); }
function settingsView(){ shell(page('Configuración','Horario y reglas',`<section class="panel wide"><div class="settings-summary"><strong>${state.settings.days}</strong><span>${state.settings.open} a ${state.settings.close}</span><span>${state.settings.message}</span></div></section>`,`<button class="primary-button" onclick="openSettingsModal()">Editar configuración</button>`)); }
function termsView(){ shell(page('Condiciones del servicio','Marco de aprobación',`<section class="panel wide"><div class="terms-box"><p>${state.terms}</p></div></section>`,isAdmin()?`<button class="primary-button" onclick="openTermsModal()">Editar condiciones</button>`:'')); }
function contractsView(){ shell(page('Contratos','Acuerdos generados desde servicios contratados',`<section class="panel wide">${contractsList()}</section>`,'')); }
function contractsList(){ const items=scoped(state.contracts); return `<div class="item-list">${items.map(x=>`<div class="contract-card"><div><span class="eyebrow">${x.number}</span><h3>${x.title}</h3><p>${x.description}</p><div class="sla-box"><span>Valor: ${money(x.price)}</span><span>Plazo: ${x.businessDays} días hábiles</span><span>Estado: ${x.status}</span><span>Condiciones: ${x.acceptedTerms?'Aceptadas':'Pendientes'}</span></div></div><div class="item-actions">${!isAdmin()&&x.status==='Pendiente aceptación'?`<button class="primary-button" onclick="acceptContract(${x.id})">Aceptar contrato</button>`:''}${isAdmin()?`<button class="ghost-button" onclick="createValuationFromContract(${x.id})">Emitir valorización</button>${controls('contracts',x.id)}`:''}</div></div>`).join('') || '<p class="empty-state">Sin contratos generados.</p>'}</div>`; }
function render(){ if(!state.user) return loginView(); const map={dashboard,clients:clientsView,projects:projectsView,requests:()=>genericView('requests','Solicitudes','Bandeja e historial',!isAdmin()?`<button class="primary-button" onclick="openRequest('Solicitud')">Nueva solicitud</button>`:''),tickets:()=>genericView('tickets','Tickets','Soporte numerado',!isAdmin()?`<button class="primary-button" onclick="openRequest('Ticket')">Abrir ticket</button>`:''),meetings:()=>genericView('meetings','Reuniones','Agenda y minutas',`<button class="primary-button" onclick="${isAdmin()?'openAdminMeetingModal':'openMeetingModal'}()">${isAdmin()?'Programar':'Solicitar'}</button>`),deliverables:()=>genericView('deliverables','Entregables','PDF, HTML, gráficos e historial',isAdmin()?`<button class="primary-button" onclick="openDeliverableModal()">Crear entregable</button>`:''),valuations:valuationsView,contracts:contractsView,messages:messagesView,terms:termsView,settings:settingsView}; (map[state.view]||dashboard)(); }
function openNotifications(){ modal('Notificaciones', `<div class="item-list">${state.notifications.map(n=>`<button class="activity-row" onclick="closeModal();setView('${n.view || 'dashboard'}')"><strong>${n.text}</strong><span>${n.time}</span></button>`).join('')}</div>`, 'close'); }
function modal(title,body,mode='form'){ document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><form class="modal" ${mode==='form'?'onsubmit="return false"':''}><div class="section-title"><div><span class="eyebrow">Portal</span><h2>${title}</h2></div><button type="button" class="ghost-button" onclick="closeModal()">Cerrar</button></div>${body}</form></div>`); }
function closeModal(){ document.querySelector('.modal-backdrop')?.remove(); }
function options(){ return scoped(state.projects).map(p=>`<option value="${p.id}">${p.name}</option>`).join(''); }
function openRequest(type){ modal(type==='Ticket'?'Abrir ticket':'Nueva solicitud', `<label>Proyecto<select id="mproject">${options()}</select></label><label>Título<input id="mtitle" required></label><label>Complejidad<select id="mcomplexity"><option>Baja</option><option selected>Media</option><option>Alta</option><option>Avanzada</option></select></label><label>Detalle<textarea id="mdetail"></textarea></label><div class="attention-box"><strong>Plazos hábiles</strong><span>El plazo se calcula solo de lunes a viernes según complejidad.</span></div><button class="primary-button" onclick="saveRequest('${type}')">Guardar</button>`); }
function saveRequest(type){ const complexity=val('mcomplexity') || 'Media'; const businessDays=businessDaysByComplexity(complexity); const item={id:Date.now(),clientId:clientId(),projectId:Number(val('mproject')),title:val('mtitle'),detail:val('mdetail'),date:'Hoy',status:'Nueva',progress:10,complexity,businessDays,dueDate:addBusinessDays(businessDays),visible:true}; if(type==='Ticket') state.tickets.unshift({...item,number:`FC-TK-${String(state.nextTicket++).padStart(4,'0')}`,priority:'Media',response:''}); else state.requests.unshift({...item,response:''}); notify(`${type} recibido. Plazo estimado: ${businessDays} días hábiles.`, type==='Ticket'?'tickets':'requests'); closeModal(); render(); }
function openDeliverableModal(){ modal('Crear entregable', `<label>Proyecto<select id="mproject">${options()}</select></label><label>Título<input id="mtitle"></label><label>Tipo<select id="mtype"><option>PDF</option><option>HTML</option><option>Gráfico</option><option>Figma</option></select></label><label>Link<input id="murl" placeholder="https://..."></label><button class="primary-button" onclick="saveDeliverable()">Publicar</button>`); }
function saveDeliverable(){ state.deliverables.unshift({id:Date.now(),clientId:clientId(),projectId:Number(val('mproject')),title:val('mtitle'),type:val('mtype'),url:val('murl'),status:'Publicado',date:'Hoy',visible:true}); notify('Entregable publicado.'); closeModal(); render(); }
function openValuationModal(){ modal('Valorizar extra', `<label>Proyecto<select id="mproject">${options()}</select></label><label>Título<input id="mtitle"></label><label>Complejidad<select id="mcomplexity"><option>Baja</option><option selected>Media</option><option>Alta</option><option>Avanzada</option></select></label><label>Detalle<textarea id="mdetail"></textarea></label><label>Precio<input id="mprice" type="number"></label><button class="primary-button" onclick="saveValuation()">Guardar</button>`); }
function saveValuation(){ const complexity=val('mcomplexity') || 'Media'; const businessDays=businessDaysByComplexity(complexity); state.valuations.unshift({id:Date.now(),clientId:clientId(),projectId:Number(val('mproject')),title:val('mtitle'),detail:val('mdetail'),price:Number(val('mprice')),complexity,businessDays,dueDate:addBusinessDays(businessDays),status:'Pendiente aprobación',paymentProof:'',acceptedTerms:false,visible:true}); notify('Valorización publicada.', 'valuations'); closeModal(); render(); }
function openCatalogModal(){ modal('Nuevo servicio/producto', `<label>Nombre<input id="catalogTitle"></label><label>Categoría<input id="catalogCategory" placeholder="Desarrollo, Reportes, Soporte..."></label><label>Descripción<textarea id="catalogDescription"></textarea></label><label>Imagen URL<input id="catalogImage" placeholder="https://..."></label><label>Valor<input id="catalogPrice" type="number"></label><label>Complejidad<select id="catalogComplexity"><option>Baja</option><option selected>Media</option><option>Alta</option><option>Avanzada</option></select></label><label>Plazo días hábiles<input id="catalogDays" type="number" value="3"></label><button class="primary-button" onclick="saveCatalogItem()">Guardar ficha</button>`); }
function saveCatalogItem(){ state.catalog.unshift({ id: Date.now(), title: val('catalogTitle'), category: val('catalogCategory'), description: val('catalogDescription'), image: val('catalogImage') || 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80', price: Number(val('catalogPrice')), complexity: val('catalogComplexity'), businessDays: Number(val('catalogDays')) || businessDaysByComplexity(val('catalogComplexity')), visible: true }); notify('Servicio agregado al catálogo.', 'valuations'); closeModal(); render(); }
function createValuationFromCatalog(id){ const item=state.catalog.find(x=>x.id===id); modal('Valorizar desde catálogo', `<label>Proyecto<select id="mproject">${options()}</select></label><div class="sla-box"><span>${item.title}</span><span>${money(item.price)}</span><span>${item.businessDays} días hábiles · ${item.complexity}</span></div><button class="primary-button" onclick="saveCatalogValuation(${id})">Emitir valorización</button>`); }
function saveCatalogValuation(id){ const item=state.catalog.find(x=>x.id===id); state.valuations.unshift({ id: Date.now(), clientId: clientId(), projectId: Number(val('mproject')), title: item.title, detail: item.description, price: item.price, complexity: item.complexity, businessDays: item.businessDays, dueDate: addBusinessDays(item.businessDays), status: 'Pendiente aprobación', paymentProof: '', acceptedTerms: false, visible: true }); notify('Valorización emitida desde catálogo.', 'valuations'); closeModal(); render(); }
function requestContract(id){ const item=state.catalog.find(x=>x.id===id); const number=`FC-CT-${String(state.contracts.length + 1).padStart(4,'0')}`; state.contracts.unshift({ id: Date.now(), number, catalogId: id, clientId: clientId(), title: item.title, description: item.description, price: item.price, complexity: item.complexity, businessDays: item.businessDays, terms: state.terms, status: 'Pendiente aceptación', acceptedTerms: false, visible: true }); notify('Contrato generado para revisión.', 'contracts'); setView('contracts'); }
function acceptContract(id){ const x=state.contracts.find(c=>c.id===id); modal('Aceptar contrato', `<div class="terms-box"><p>${x.terms}</p></div><div class="sla-box"><span>${x.title}</span><span>${money(x.price)}</span><span>${x.businessDays} días hábiles · ${x.complexity}</span></div><label><input id="acceptContractTerms" type="checkbox"> Acepto las condiciones y solicito emisión de valorización</label><button class="primary-button" onclick="saveContractAcceptance(${id})">Aceptar contrato</button>`); }
function saveContractAcceptance(id){ const x=state.contracts.find(c=>c.id===id); if(!document.getElementById('acceptContractTerms')?.checked) return alert('Debes aceptar las condiciones del contrato.'); x.acceptedTerms=true; x.status='Aceptado por cliente'; notify('Contrato aceptado por cliente.', 'contracts'); closeModal(); render(); }
function createValuationFromContract(id){ const x=state.contracts.find(c=>c.id===id); state.valuations.unshift({ id: Date.now(), clientId: x.clientId, projectId: scoped(state.projects)[0]?.id, title: x.title, detail: x.description, price: x.price, complexity: x.complexity, businessDays: x.businessDays, dueDate: addBusinessDays(x.businessDays), status: 'Pendiente aprobación', paymentProof: '', acceptedTerms: x.acceptedTerms, visible: true }); x.status='Valorización emitida'; notify('Valorización emitida desde contrato.', 'valuations'); setView('valuations'); }
function approveValuation(id){ const x=state.valuations.find(i=>i.id===id); modal('Aprobar valorización', `<div class="terms-box"><p>${state.terms}</p></div><label><input id="acceptTerms" type="checkbox"> Acepto las condiciones del servicio</label><label>Adjuntar comprobante de pago<input id="proof" type="file"></label><button class="primary-button" onclick="saveClientApproval(${id})">Enviar aprobación</button>`); }
function saveClientApproval(id){ const x=state.valuations.find(i=>i.id===id); const proof=document.getElementById('proof')?.files?.[0]?.name || ''; if(!document.getElementById('acceptTerms')?.checked) return alert('Debes aceptar las condiciones del servicio.'); if(!proof) return alert('Debes adjuntar el comprobante de pago.'); x.acceptedTerms=true; x.paymentProof=proof; x.status='Pago enviado'; notify('Cliente aprobó valorización y adjuntó comprobante.', 'valuations'); closeModal(); render(); }
function rejectValuation(id){ const x=state.valuations.find(i=>i.id===id); x.status='Rechazado por cliente'; notify('Valorización rechazada por cliente.', 'valuations'); render(); }
function openClientModal(){ modal('Crear cliente', `<label>Empresa<input id="cname"></label><label>Contacto<input id="ccontact"></label><label>Email<input id="cemail"></label><label>Clave<input id="cpass"></label><button class="primary-button" onclick="saveClient()">Guardar</button>`); }
function saveClient(){ const id=Date.now(), name=val('cname'), email=val('cemail'), password=val('cpass'); state.clients.push({id,name,contact:val('ccontact'),email,password,plan:'Nuevo cliente',initials:name.split(' ').map(w=>w[0]).join('').slice(0,2).toUpperCase()}); users.push({email,password,role:'client',clientId:id}); state.selectedClientId=id; notify('Cliente creado.'); closeModal(); render(); }
function openSettingsModal(){ modal('Configuración', `<label>Días<input id="sdays" value="${state.settings.days}"></label><label>Apertura<input id="sopen" value="${state.settings.open}"></label><label>Cierre<input id="sclose" value="${state.settings.close}"></label><label>Mensaje<textarea id="smsg">${state.settings.message}</textarea></label><button class="primary-button" onclick="saveSettings()">Guardar</button>`); }
function saveSettings(){ state.settings={days:val('sdays'),open:val('sopen'),close:val('sclose'),message:val('smsg')}; notify('Configuración actualizada.'); closeModal(); render(); }
function openOnboarding(){ modal('Onboarding del portal', `<div class="onboarding-grid"><article><strong>1. Revisa tu panel</strong><span>Encuentra proyectos, solicitudes, tickets, reuniones y valorizaciones en un solo lugar.</span></article><article><strong>2. Sigue tus proyectos</strong><span>Cada proyecto muestra avance, próximo paso e hitos en línea de tiempo.</span></article><article><strong>3. Valida entregables</strong><span>Abre reportes, gráficos, PDF o enlaces publicados por FullCheck.</span></article><article><strong>4. Aprueba extras</strong><span>Revisa valor, plazo, condiciones y adjunta comprobante cuando apruebes un trabajo adicional.</span></article></div>`, 'close'); }
function openMilestoneModal(projectId=''){ modal('Agregar hito', `<label>Proyecto<select id="milestoneProject">${options()}</select></label><label>Hito<input id="milestoneTitle" placeholder="Ej: Subida imágenes"></label><label>Fecha<input id="milestoneDate" placeholder="05/05/2026"></label><label>Asignado a<select id="milestoneAssigned"><option>FullCheck</option><option>Cliente</option><option>Ambos</option></select></label><label>Estado<select id="milestoneStatus"><option>Pendiente</option><option>En proceso</option><option>Completado</option></select></label><button class="primary-button" onclick="saveMilestone(${projectId || 0})">Guardar hito</button>`); if(projectId) document.getElementById('milestoneProject').value=projectId; }
function saveMilestone(forcedProjectId){ const projectId=forcedProjectId || Number(val('milestoneProject')); const project=state.projects.find(p=>p.id===projectId); state.milestones.unshift({ id: Date.now(), clientId: project?.clientId || clientId(), projectId, title: val('milestoneTitle'), date: val('milestoneDate'), assignedTo: val('milestoneAssigned'), status: val('milestoneStatus'), visible: true }); notify('Hito registrado en línea de tiempo.', 'projects'); closeModal(); render(); }
function toggleMilestone(id){ const x=state.milestones.find(m=>m.id===id); x.status=x.status==='Completado'?'Pendiente':'Completado'; notify('Hito actualizado.', 'projects'); render(); }
function openMeetingModal(){ modal('Solicitar reunión', `<label>Motivo<input id="mtitle"></label><label>Fecha<input id="mdate"></label><label>Hora<input id="mtime"></label><button class="primary-button" onclick="saveMeeting(false)">Enviar</button>`); }
function openAdminMeetingModal(){ modal('Programar reunión', `<label>Proyecto<select id="mproject">${options()}</select></label><label>Título<input id="mtitle"></label><label>Fecha<input id="mdate"></label><label>Hora<input id="mtime"></label><label>Link<input id="mlink"></label><label>Minuta<textarea id="mnotes"></textarea></label><button class="primary-button" onclick="saveMeeting(true)">Programar</button>`); }
function saveMeeting(admin){ state.meetings.unshift({id:Date.now(),clientId:clientId(),projectId:Number(val('mproject'))||scoped(state.projects)[0]?.id,title:val('mtitle'),date:val('mdate'),time:val('mtime'),link:val('mlink'),notes:val('mnotes'),status:admin?'Confirmada':'Solicitada',visible:true}); notify('Reunión registrada.'); closeModal(); render(); }
function manageRequest(id){ const x=state.requests.find(i=>i.id===id); modal('Gestionar solicitud', `<label>Estado<select id="mstatus"><option>Nueva</option><option>En revisión</option><option>En ejecución</option><option>Completada</option><option>Cerrada</option></select></label><label>Respuesta<textarea id="mresponse">${x.response||''}</textarea></label><button class="primary-button" onclick="saveRequestAdmin(${id})">Guardar</button>`); }
function saveRequestAdmin(id){ const x=state.requests.find(i=>i.id===id); x.status=val('mstatus'); x.progress=progressByStatus(x.status); x.response=val('mresponse'); notify('Solicitud actualizada.', 'requests'); closeModal(); render(); }
function answerTicket(id){ const x=state.tickets.find(i=>i.id===id); modal(`Responder ${x.number}`, `<label>Estado<select id="mstatus"><option>Abierto</option><option>En revisión</option><option>Resuelto</option><option>Cerrado</option></select></label><label>Respuesta<textarea id="mresponse">${x.response||''}</textarea></label><button class="primary-button" onclick="saveTicket(${id})">Guardar</button>`); }
function saveTicket(id){ const x=state.tickets.find(i=>i.id===id); x.status=val('mstatus'); x.response=val('mresponse'); notify('Ticket respondido.'); closeModal(); render(); }
function editMeeting(id){ const x=state.meetings.find(i=>i.id===id); modal('Gestionar reunión', `<label>Estado<select id="mstatus"><option>Solicitada</option><option>Confirmada</option><option>Reagendada</option><option>Realizada</option><option>Cancelada</option></select></label><label>Link<input id="mlink" value="${x.link||''}"></label><label>Minuta<textarea id="mnotes">${x.notes||''}</textarea></label><button class="primary-button" onclick="saveMeetingAdmin(${id})">Guardar</button>`); }
function saveMeetingAdmin(id){ const x=state.meetings.find(i=>i.id===id); x.status=val('mstatus'); x.link=val('mlink'); x.notes=val('mnotes'); notify('Reunión actualizada.'); closeModal(); render(); }
function manageValuation(id){ const x=state.valuations.find(i=>i.id===id); modal('Gestionar valorización', `<label>Estado<select id="mstatus"><option>Pendiente aprobación</option><option>Pago enviado</option><option>Pago validado - en ejecución</option><option>Completado</option><option>Rechazado</option><option>Facturado</option></select></label><label>Precio<input id="mprice" type="number" value="${x.price}"></label><div class="sla-box"><span>Comprobante: ${x.paymentProof || 'No adjuntado'}</span><span>Condiciones aceptadas: ${x.acceptedTerms ? 'Sí' : 'No'}</span></div><button class="primary-button" onclick="saveValuationStatus(${id})">Guardar</button>`); }
function saveValuationStatus(id){ const x=state.valuations.find(i=>i.id===id); x.status=val('mstatus'); x.price=Number(val('mprice')); if(x.status==='Pago validado - en ejecución') createProjectFromValuation(x); notify('Valorización actualizada.', 'valuations'); closeModal(); render(); }
function createProjectFromValuation(x){ if(state.projects.some(p=>p.fromValuationId===x.id)) return; state.projects.push({ id: Date.now(), clientId: x.clientId, fromValuationId: x.id, name: x.title, phase: 'Desarrollo', status: 'En progreso', progress: 5, due: x.dueDate, next: 'Trabajo iniciado tras validación de pago', visible: true }); }
function openTermsModal(){ modal('Editar condiciones', `<label>Condiciones<textarea id="termsText">${state.terms}</textarea></label><button class="primary-button" onclick="saveTerms()">Guardar condiciones</button>`); }
function saveTerms(){ state.terms=val('termsText'); notify('Condiciones del servicio actualizadas.', 'terms'); closeModal(); render(); }
function setProgress(id,v){ const x=state.projects.find(p=>p.id===id); x.progress=Math.max(0,Math.min(100,Number(v))); notify('Avance actualizado.'); render(); }
function setPhase(id,v){ const x=state.projects.find(p=>p.id===id); x.phase=v; notify('Pipeline actualizado.'); render(); }
function toggleVisible(col,id){ const x=state[col].find(i=>i.id===id); x.visible=x.visible===false; render(); }
function removeItem(col,id){ if(confirm('¿Eliminar registro?')){ state[col]=state[col].filter(i=>i.id!==id); render(); } }
function deleteClient(id){ if(!confirm('¿Eliminar cliente y todos sus datos?')) return; ['projects','updates','requests','tickets','meetings','deliverables','valuations','files','messages'].forEach(k=>state[k]=state[k].filter(i=>i.clientId!==id)); state.clients=state.clients.filter(c=>c.id!==id); for(let i=users.length-1;i>=0;i--) if(users[i].clientId===id) users.splice(i,1); state.selectedClientId=state.clients[0]?.id||0; render(); }
function sendMessage(e){ e.preventDefault(); const text=val('msg'); if(!text) return; state.messages.push({id:Date.now(),clientId:clientId(),from:isAdmin()?'FullCheck':'Cliente',text,time:'Ahora',visible:true}); notify('Nuevo mensaje.'); render(); }
loginView();
